package com.hj.core.enums;

/**
 * 位置 垂直 水平 etc.
 */
public enum WaveMarkPosition {
    ALIGN_LEFT,ALIGN_CENTER,ALIGN_RIGHT,ALIGN_JUSTIFIED,ALIGN_TOP,ALIGN_MIDDLE,ALIGN_BOTTOM,ALIGN_BASELINE,ALIGN_JUSTIFIED_ALL
}
